### ISSUE TITLE
Data sorting module

### ISSUE THREAD

**Issue by ashketchupppp** [ashketchupppp/sysdev2coursework#26]

**Comment by billyrturner** [comment]
See my sort.py in my branch for my solution to this. You'll see that I've added some example data to help show what the code does. The names of dictionaries will of course have to be changed to reflect those used by the data filter module

**Comment by ashketchupppp** [comment]
Nice work on the sorting, I have never looked at lambda functions but they look very useful.

1. Could you put it in a separate folder with an extra file called _ _init_ _.py to make it a module
2. Adding some tests would be good. Trying edge cases such as passing the functions values that are invalid etc. etc. to see how it holds up
3. It is standard practice for all imports to go to the top of the file
For these ones ^^^^ I suggest you look at my csvreader branch and pretty much copy it.

For the actual code
1. you put three functions but you could have two or maybe even one, merging crimesort and distsort as you could pass the following things as parameters
- 'Distance (km)' 
- Passing the dictionary to sort
- A reverse value so you can choose to sort ascending or descending
2. A good rule of thumb for functions is that they do one thing only. Here you sort the dictionary and you print it, maybe I only want to sort the dict? A better practice would be to return the the sorted dict at the end of the function, that way you keep to the rule and if you want to print it then they still can.

Good stuff :)

**Comment by billyrturner** [comment]
Hey, I've acted on your feedback and made changes in my branch
