### ISSUE TITLE
Function that finds a single (dict) record that has a matching value

### ISSUE THREAD

**Issue by ashketchupppp** [ashketchupppp/sysdev2coursework#34]
This will be used for searching for the EX postcodes which will be stored as a list of dictionaries.

The module must have a function which is passed three variables: a list of dictionaries, a value to search for and a dictionary key to search. It must then go through the list of dictionaries, checking each dictionary with the key that was passed to it, to see if the key matches the value provided. The function must return the dictionary that was found, if one was found. If there is no match then it returns a -1.

This function must be unit tested. It cannot throw an error if the given key isn't in a dictionary entry.

**Comment by cuthbert1221** [comment]
Required for the Command which searches the postcodes
In the interest of time I'll have a look a this issue as well.
