### ISSUE TITLE
Getting import issues when creating a test for the filter module - "no module named 'ui' "

### ISSUE THREAD

**Issue by billyrturner** [ashketchupppp/sysdev2coursework#74]
![Screenshot 2020-04-04 at 17.45.35.png](https://images.zenhubusercontent.com/5e665ee38168d5308058b6e7/70035d04-4a05-419f-a5d1-5d6c29235e5f)

See test_filter.py in the branch Billy-cleanup

**Comment by ashketchupppp** [comment]
can you verify this is still an issue please?

**Comment by ashketchupppp** [comment]
I think this has been solved
