### ISSUE TITLE
Command which searches the postcodes and gives the lat and long of an EX postcode

### ISSUE THREAD

**Issue by ashketchupppp** [ashketchupppp/sysdev2coursework#8]
This must use the code from the data searching module. It uses the data searching module to find a dictionary with a particular postcode in the postcodes that are loaded when the program starts up. 

The command must prompt the user for a postcode and then searches the postcodes list for that postcode, if a matching postcode is found then it will get the co-ordinate values from the returned dictionary and print them out to the screen. If there was no match then the user must be notified that the postcode they entered could not be found.

**Comment by cuthbert1221** [comment]
@ashketchupppp I can do this one if needed?
