### ISSUE TITLE
Function to find the distance between two (lat & long) co-ordinates

### ISSUE THREAD

**Issue by ashketchupppp** [ashketchupppp/sysdev2coursework#9]

**Comment by cuthbert1221** [comment]
The function in libs/compare-cord.py on Jacob's branch, takes in two co-ords and a radius and determines if the co-ords are inside or outside the radius. 
It needs improving but could help to get started.
[https://github.com/ashketchupppp/sysdev2coursework/blob/Jacob-inital/libs/compare-co-ords.py](url)

**Comment by ashketchupppp** [comment]
Would be a good idea to put the geodist file in this module

**Comment by cuthbert1221** [comment]
Yes, I'll add the geodist file, and redo the function accordingly.
